# Generated by Django 2.2.10 on 2020-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200305_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.URLField(default='asdas'),
            preserve_default=False,
        ),
    ]
